"""change nullability

Revision ID: a5da0b39944e
Revises: 
Create Date: 2021-08-12 15:05:36.780134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5da0b39944e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=20), nullable=False),
    sa.Column('product_description', sa.String(), nullable=False),
    sa.Column('product_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_description'),
    sa.UniqueConstraint('product_name')
    )
    op.create_table('User_Accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('mailing_address', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('subscriber', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Owned_Items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['Products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User_Accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Owned_Items')
    op.drop_table('User_Accounts')
    op.drop_table('Products')
    # ### end Alembic commands ###
