"""Added mailing table

Revision ID: 08ca75016cb9
Revises: 1cd994106fd5
Create Date: 2021-09-01 10:15:50.296203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ca75016cb9'
down_revision = '1cd994106fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Mailing_Addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('organization', sa.String(length=20), nullable=True),
    sa.Column('po_box', sa.String(length=40), nullable=False),
    sa.Column('state', sa.Enum('Alabama', 'Alaska', 'American_Samoa', 'Arazona', 'Arkansas', 'California', 'Colorado', 'Conneticut', 'Delaware', 'District_Of_Columia', 'Federated_States_Of_Micronesia', 'Florida', 'Georgia', 'Guam', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Luisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New_Hampshire', 'New_Jersey', 'New_Mexico', 'New_York', 'North_Carolina', 'North_Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode_Island', 'South_Carolina', 'South_Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia_Islands', 'Virginia', 'Washington', 'West_Virginia', 'Wisconsin', 'Wyoming', name='usstateenum'), nullable=False),
    sa.Column('zip', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('User_Accounts', 'mailing_address')
    op.drop_column('User_Accounts', 'zip_code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User_Accounts', sa.Column('zip_code', sa.VARCHAR(), nullable=True))
    op.add_column('User_Accounts', sa.Column('mailing_address', sa.VARCHAR(), nullable=True))
    op.drop_table('Mailing_Addresses')
    # ### end Alembic commands ###
