"""empty message

Revision ID: 969af5bbbed5
Revises: 
Create Date: 2022-01-13 19:51:15.382056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969af5bbbed5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Adventure_Kits',
    sa.Column('cover', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('product_details', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date_added', sa.Date(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('pre_order', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Mini_Shrines',
    sa.Column('cover', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('product_details', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date_added', sa.Date(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('pre_order', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('mini_name', sa.String(length=20), nullable=False),
    sa.Column('mini_font', sa.String(length=20), nullable=False),
    sa.Column('bio_message', sa.String(length=100), nullable=False),
    sa.Column('bio_font', sa.String(length=20), nullable=False),
    sa.Column('globe_color', sa.String(length=20), server_default='clear', nullable=False),
    sa.Column('back_plate_wood_species', sa.String(length=20), nullable=False),
    sa.Column('bottom_plate_wood_species', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User_Accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('subscriber', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Mailing_Addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=40), server_default='PO BOX', nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('organization', sa.String(length=20), nullable=True),
    sa.Column('po_box', sa.String(length=40), server_default='N/A', nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('zip', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User_Accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Owned_Items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('kit_id', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.Date(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kit_id'], ['Adventure_Kits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User_Accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Owned_Items')
    op.drop_table('Mailing_Addresses')
    op.drop_table('User_Accounts')
    op.drop_table('Mini_Shrines')
    op.drop_table('Adventure_Kits')
    # ### end Alembic commands ###
